# Generated by Django 4.0.4 on 2022-05-07 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)])),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_code', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(4), django.core.validators.MinLengthValidator(4)])),
                ('bank_address', models.TextField()),
            ],
        ),
    ]
