# Generated by Django 4.0.4 on 2022-07-06 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.BigIntegerField()),
                ('tenure', models.IntegerField()),
                ('interest', models.FloatField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
