# Generated by Django 4.0.4 on 2022-05-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='uploads/documents/')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc', models.IntegerField()),
                ('aadhaar_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_aadhaar', to='loan.document')),
                ('pan_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pan', to='loan.document')),
                ('salary_slips', models.ManyToManyField(related_name='user_salaryslips', to='loan.document')),
                ('user_bank_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bank_details', to='loan.userbankdata')),
            ],
        ),
    ]
