# Generated by Django 4.0.4 on 2022-07-15 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_loan_repaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_repaid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In_Review', 'In Review'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='In_Review', max_length=15),
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_interest', models.FloatField()),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_offered_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='loan_requests', to='loan.loanrequest'),
        ),
    ]
