# Generated by Django 4.0.4 on 2022-07-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userbankdata_remove_user_user_data_userdocuments_and_more'),
        ('loan', '0002_document_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='aadhaar_card',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='salary_slips',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user_bank_info',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='UserBankData',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
