# Generated by Django 4.0.4 on 2022-08-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loan_is_loan_repaid_loan_loan_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_request_accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_request_accepted', to='loan.loanrequest'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='tenure',
            field=models.IntegerField(null=True),
        ),
    ]
