# Generated by Django 4.0.4 on 2022-08-05 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0004_loan_loan_request_accepted_loanrequest_tenure'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_interest', models.FloatField()),
                ('tenure', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=15)),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_offered_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_request_accepted',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='requests',
        ),
        migrations.DeleteModel(
            name='LoanRequest',
        ),
        migrations.AddField(
            model_name='loan',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='loan_bids', to='loan.loanbid'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_bid_accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_bid_accepted', to='loan.loanbid'),
        ),
    ]
