# Generated by Django 4.0.4 on 2022-07-06 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='uploads/documents/')),
            ],
        ),
    ]
