# Generated by Django 4.0.4 on 2022-08-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocuments',
            name='aadhaar_card',
        ),
        migrations.RemoveField(
            model_name='userdocuments',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='userdocuments',
            name='salary_slips',
        ),
        migrations.RemoveField(
            model_name='userdocuments',
            name='user_bank_info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_bank_data',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_documents',
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserBankData',
        ),
        migrations.DeleteModel(
            name='UserDocuments',
        ),
    ]
