# Generated by Django 4.0.4 on 2022-08-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userdocuments_aadhaar_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.BigIntegerField(default=0),
        ),
    ]
