# Generated by Django 4.0.4 on 2022-07-04 15:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('users', '0003_user_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)])),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_code', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(4), django.core.validators.MinLengthValidator(4)])),
                ('bank_address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_data',
        ),
        migrations.CreateModel(
            name='UserDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc', models.IntegerField()),
                ('aadhaar_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_aadhaar', to='document.document')),
                ('pan_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pan', to='document.document')),
                ('salary_slips', models.ManyToManyField(related_name='user_salaryslips', to='document.document')),
                ('user_bank_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bank_details', to='users.userbankdata')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_bank_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bank_data', to='users.userbankdata'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to='users.userdocuments'),
        ),
    ]
