# Generated by Django 4.0.4 on 2022-07-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userbankdata_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankdata',
            name='account_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userbankdata',
            name='bank_code',
            field=models.IntegerField(),
        ),
    ]
